sudo: required
services:
  - docker

before_install:
  - docker build -t farshid91/React-Docker-test -f Dockerfile.dev .

script:
  - docker run farshid91/React-Docker-test npm run test -- --coverage

